import React, { useEffect, useState } from 'react';
import { useNavigate, useLocation } from 'react-router-dom';
import { motion, AnimatePresence } from 'framer-motion';
import { MessageCircle, X, ChevronRight, Sparkles } from 'lucide-react';
import { useAuth } from '@/context/AuthContext';
import { getDeepstreamClient } from '@/lib/deepstream';
import { AnimatedReactionIcon } from './AnimatedReactionIcons';

export interface FeedAuthorNotification {
  id: string;
  type: 'COMMENT' | 'REACTION' | 'AI_COMMENT';
  postId: string;
  postAuthorId: string;
  actorId: string;
  actorName: string;
  actorSubtitle?: string;
  actorAvatar?: string;
  contentPreview?: string;
  reaction?: string | null;
  schoolId?: string;
  createdAt: string;
}

export const FeedRealtimeNotificationBalloon: React.FC = () => {
  const { user } = useAuth();
  const navigate = useNavigate();
  const location = useLocation();
  const [notifications, setNotifications] = useState<FeedAuthorNotification[]>([]);

  useEffect(() => {
    if (!user?.id) return;

    const client = getDeepstreamClient();
    if (!client) return;

    const handleNotificationEvent = (payload: FeedAuthorNotification) => {
      // Only process notifications intended for the current user and not generated by themselves
      if (!payload || payload.postAuthorId !== user.id || payload.actorId === user.id) {
        return;
      }

      setNotifications(prev => {
        // Avoid duplicates within a short window
        const filtered = prev.filter(n => n.id !== payload.id);
        return [payload, ...filtered].slice(0, 3); // keep max 3 notifications
      });
    };

    const userSpecificTopic = `feed-author-notification:${user.id}`;
    const globalTopic = 'feed-author-notification';

    try {
      client.event.subscribe(userSpecificTopic, handleNotificationEvent);
      client.event.subscribe(globalTopic, handleNotificationEvent);
    } catch (err) {
      console.warn('[FEED NOTIFICATION SUBSCRIBER ERROR]', err);
    }

    return () => {
      try {
        client.event.unsubscribe(userSpecificTopic, handleNotificationEvent);
        client.event.unsubscribe(globalTopic, handleNotificationEvent);
      } catch (err) {
        // cleanup ignore
      }
    };
  }, [user?.id]);

  // Auto-dismiss notifications after 8 seconds
  useEffect(() => {
    if (notifications.length === 0) return;

    const timer = setTimeout(() => {
      setNotifications(prev => prev.slice(0, -1));
    }, 8000);

    return () => clearTimeout(timer);
  }, [notifications]);

  const handleDismiss = (e: React.MouseEvent, id: string) => {
    e.stopPropagation();
    setNotifications(prev => prev.filter(n => n.id !== id));
  };

  const handleBalloonClick = (notif: FeedAuthorNotification) => {
    // Dismiss clicked notification
    setNotifications(prev => prev.filter(n => n.id !== notif.id));

    const currentPath = location.pathname;
    let targetBase = '/panel';
    if (currentPath.startsWith('/admin')) targetBase = '/admin';
    else if (currentPath.startsWith('/console')) targetBase = '/console';
    else if (currentPath.startsWith('/panel')) targetBase = '/panel';

    const targetUrl = `${targetBase}/feed?postId=${notif.postId}`;

    navigate(targetUrl);

    // Dispatch custom event for instant focus and opening of detail modal
    const dispatchFocus = () => {
      window.dispatchEvent(
        new CustomEvent('focus-feed-post', {
          detail: {
            postId: notif.postId,
            openComments: true
          }
        })
      );
    };

    dispatchFocus();
    setTimeout(dispatchFocus, 100);
    setTimeout(dispatchFocus, 400);
  };

  if (!user || notifications.length === 0) return null;

  return (
    <aside aria-label="Notificaciones del muro" className="fixed top-4 right-4 sm:right-6 z-[999999] flex flex-col gap-2.5 max-w-sm sm:max-w-md w-full pointer-events-none">
      <AnimatePresence>
        {notifications.map(notif => {
          const isComment = notif.type === 'COMMENT';
          const isAi = notif.type === 'AI_COMMENT';
          const isReaction = notif.type === 'REACTION';

          return (
            <motion.div
              key={notif.id}
              initial={{ opacity: 0, y: -25, scale: 0.92, filter: 'blur(4px)' }}
              animate={{ opacity: 1, y: 0, scale: 1, filter: 'blur(0px)' }}
              exit={{ opacity: 0, scale: 0.9, y: -15, filter: 'blur(4px)' }}
              transition={{ type: 'spring', stiffness: 450, damping: 28 }}
              onClick={() => handleBalloonClick(notif)}
              className="pointer-events-auto group cursor-pointer relative overflow-hidden bg-white/95 dark:bg-slate-900/95 border border-slate-200/90 dark:border-slate-800 backdrop-blur-xl shadow-2xl rounded-2xl p-3.5 transition-all hover:ring-2 hover:ring-emerald-500/50 hover:shadow-emerald-500/10"
            >
              {/* Subtle top indicator bar */}
              <div className="absolute top-0 left-0 right-0 h-1 bg-gradient-to-r from-emerald-500 via-teal-400 to-indigo-500" />

              <div className="flex items-start gap-3">
                {/* Avatar with reaction / comment badge */}
                <div className="relative shrink-0 mt-0.5">
                  <div className="w-10 h-10 rounded-full bg-gradient-to-br from-emerald-600 to-teal-700 text-white font-bold flex items-center justify-center text-sm overflow-hidden shadow-xs">
                    {notif.actorAvatar ? (
                      <img
                        src={notif.actorAvatar}
                        alt={notif.actorName}
                        className="w-full h-full object-cover"
                      />
                    ) : (
                      notif.actorName.charAt(0).toUpperCase()
                    )}
                  </div>

                  {/* Corner Badge */}
                  <div className="absolute -bottom-1 -right-1 w-5 h-5 rounded-full bg-white dark:bg-slate-800 shadow-md flex items-center justify-center border border-slate-100 dark:border-slate-700">
                    {isReaction && notif.reaction ? (
                      <AnimatedReactionIcon reaction={notif.reaction} size={14} />
                    ) : isAi ? (
                      <Sparkles className="w-3 h-3 text-indigo-500" />
                    ) : (
                      <MessageCircle className="w-3 h-3 text-emerald-600 dark:text-emerald-400" />
                    )}
                  </div>
                </div>

                {/* Notification Content */}
                <div className="flex-1 min-w-0 pr-4">
                  <div className="flex items-center gap-1.5 flex-wrap">
                    <span className="text-xs font-bold text-slate-900 dark:text-white truncate">
                      {notif.actorName}
                    </span>
                    {notif.actorSubtitle && (
                      <span className="text-[10.5px] font-medium px-1.5 py-0.2 bg-slate-100 dark:bg-slate-800 text-slate-600 dark:text-slate-300 rounded-md truncate max-w-[170px]">
                        {notif.actorSubtitle}
                      </span>
                    )}
                  </div>

                  <p className="text-xs text-slate-600 dark:text-slate-300 mt-0.5 leading-snug">
                    {isReaction ? (
                      <span>ha reaccionado a tu publicación.</span>
                    ) : isAi ? (
                      <span>ha respondido como Asistente IA a tu publicación.</span>
                    ) : (
                      <span>ha comentado tu publicación.</span>
                    )}
                  </p>

                  {/* Preview text if available */}
                  {notif.contentPreview && !isReaction && (
                    <p className="text-[11px] text-slate-500 dark:text-slate-400 mt-1 line-clamp-1 italic bg-slate-50 dark:bg-slate-800/60 px-2 py-0.5 rounded-lg border border-slate-100 dark:border-slate-800/80">
                      "{notif.contentPreview}"
                    </p>
                  )}

                  {/* Click to view CTA */}
                  <div className="flex items-center gap-1 mt-2 text-[10.5px] font-semibold text-emerald-600 dark:text-emerald-400 group-hover:translate-x-0.5 transition-transform">
                    <span>Ver publicación</span>
                    <ChevronRight className="w-3 h-3" />
                  </div>
                </div>

                {/* Close Button */}
                <button
                  type="button"
                  onClick={(e) => handleDismiss(e, notif.id)}
                  aria-label="Cerrar notificación"
                  className="shrink-0 p-1 text-slate-400 hover:text-slate-600 dark:hover:text-slate-200 rounded-lg hover:bg-slate-100 dark:hover:bg-slate-800 transition-colors cursor-pointer"
                >
                  <X className="w-3.5 h-3.5" />
                </button>
              </div>
            </motion.div>
          );
        })}
      </AnimatePresence>
    </aside>
  );
};
